name: Sync main to origin

on:
  schedule:
    - cron: "0 0 * * 1"  # 每周一的 00:00 自动运行一次
  workflow_dispatch:      # 支持手动触发工作流

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      # 检出 main 分支的代码
      - name: Checkout main branch
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: main

      # 设置 git 用户信息
      - name: Set up Git user
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      # 拉取更新并推送到 origin
      - name: Sync main to origin
        run: |
          set -e
          git fetch origin
          if ! git diff --quiet origin/main; then
            git pull origin main --rebase  # 拉取远程更新并重放本地更改
          fi
          git push origin main:origin
